---
networks:
  backend:
    external: true
services:
  app:
    container_name: portainer-agent-prod-1
    deploy:
      mode: global
    image: portainer/agent:2.20.3-alpine
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - backend
    restart: always
