---
networks:
  frontend:
    external: true
  backend:
    external: true
services:
  adminer:
    container_name: adminer-prod-1
    image: adminer:4.8.1
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.services.adminer-prod-1.loadbalancer.server.port=8080
      - traefik.http.services.adminer-prod-1.loadbalancer.server.scheme=http
      - traefik.http.routers.adminer-prod-1-https.entrypoints=websecure
      - traefik.http.routers.adminer-prod-1-https.rule=Host(`adminer-prod-1.srv-prod-2.home.kinzoku.dev`)
      - traefik.http.routers.adminer-prod-1-https.tls=true
      - traefik.http.routers.adminer-prod-1-https.tls.certresolver=cloudflare
    networks:
      - frontend
      - backend
    restart: unless-stopped
