---
- hosts: "{{ hosts }}"
  tasks:
    - name: create remote project dir
      shell: |
        mkdir -p {{ remote_project_dir }}

    - name: copy docker-compose file
      copy:
        src: "{{ local_project_dir }}/{{ item }}"
        dest: "{{ remote_project_dir }}/{{ item }}"
      loop:
        - docker-compose.yaml

    - name: copy .env file if needed
      when: copy_env == "true"
      copy:
        src: "{{ local_project_dir }}/{{ item }}"
        dest: "{{ remote_project_dir }}/{{ item }}"
      loop:
        - .env

    - name: deploy docker-compose project
      community.docker.docker_compose_v2:
        project_src: "{{ remote_project_dir }}"
        files:
          - docker-compose.yaml
        state: present
        pull: policy
        remove_orphans: true
