---
networks:
  frontend:
    external: true
  backend:
    external: true
volumes:
  postgres-data:
services:
  postgres:
    container_name: pgdb-prod-1
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file: ./.env
    ports:
      - 5432:5432
    networks:
      - frontend
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /etc/ssl/cert.pem:/etc/ssl/cert.pem
      - /etc/ssl/cert-key.pem:/etc/ssl/cert-key.pem
      - /etc/ssl/ca.pem:/etc/ssl/ca.pem
    command:
      - "-c"
      - "ssl=on"
      - "-c"
      - "ssl_cert_file=/etc/ssl/cert.pem"
      - "-c"
      - "ssl_key_file=/etc/ssl/cert-key.pem"
      - "-c"
      - "ssl_ca_file=/etc/ssl/ca.pem"
    restart: unless-stopped
