---
networks:
  frontend:
    external: true
  backend:
    external: true
services:
  loki:
    image: grafana/loki:main
    container_name: loki-prod-1
    volumes:
      - ./config:/etc/loki
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yaml
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.loki-prod-1-http.entrypoints=web
      - traefik.http.routers.loki-prod-1-http.rule=Host(`loki-prod-1.srv-prod-1.home.kinzoku.dev`)
      - traefik.http.routers.loki-prod-1-https.entrypoints=websecure
      - traefik.http.routers.loki-prod-1-https.rule=Host(`loki-prod-1.srv-prod-1.home.kinzoku.dev`)
      - traefik.http.routers.loki-prod-1-https.tls=true
      - traefik.http.routers.loki-prod-1-https.tls.certresolver=cloudflare
    networks:
      - frontend
      - backend
