---
networks:
  frontend:
    external: true
  backend:
    external: true
services:
  bind9:
    container_name: dns-prod-1
    image: ubuntu/bind9:9.18-23.04_beta
    environment:
      - BIND9_USER=root
      - TZ=America/Chicago
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
      - /etc/bind/named.conf.key:/etc/bind/named.conf.key
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: unless-stopped
    networks:
      - frontend
      - backend
