---
networks:
  frontend:
    external: true
  backend:
    external: true
volumes:
  prometheus-data:
    driver: local
services:
  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus-prod-1
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus-data:/prometheus
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.prometheus-prod-1-http.entrypoints=web
      - traefik.http.routers.prometheus-prod-1-http.rule=Host(`prometheus-prod-1.srv-prod-1.home.kinzoku.dev`)
      - traefik.http.routers.prometheus-prod-1-https.entrypoints=websecure
      - traefik.http.routers.prometheus-prod-1-https.rule=Host(`prometheus-prod-1.srv-prod-1.home.kinzoku.dev`)
      - traefik.http.routers.prometheus-prod-1-https.tls=true
      - traefik.http.routers.prometheus-prod-1-https.tls.certresolver=cloudflare
    networks:
      - frontend
      - backend
    restart: unless-stopped
