---
- hosts: "{{ hosts }}"
  become: true
  tasks:
    - name: install core packages
      apt:
        name:
          - prometheus-node-exporter
          - nfs-common
          - unzip
        update_cache: true
