---
- hosts: "{{ hosts }}"
  tasks:
    - name: create remote project dir
      shell: |
        mkdir -p {{ remote_project_dir }}

    - name: copy docker-compose file
      copy:
        src: "{{ local_project_dir }}/{{ item }}"
        dest: "{{ remote_project_dir }}/{{ item }}"
      loop:
        - docker-compose.yaml

    - name: copy .env file if needed
      when: copy_env is defined and copy_env == "true"
      copy:
        src: "{{ local_project_dir }}/{{ item }}"
        dest: "{{ remote_project_dir }}/{{ item }}"
      loop:
        - .env

    - name: copy other files
      when: extra_files is defined
      block:
        - name: create dest folders if needed
          shell: |
            mkdir -p {{ item.dest }} -m 777
          loop: "{{ extra_files }}"
          when: item.dest is defined
        - name: copy files
          copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest | default(remote_project_dir) }}"
          loop: "{{ extra_files }}"

    - name: copy other folders
      when: extra_folders is defined
      block:
        - name: create dest folders if needed
          shell: |
            mkdir -p {{ item.dest }} -m 777
          loop: "{{ extra_folders }}"
          when: item.dest is defined
        - name: copy folders
          copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest | default(remote_project_dir) }}"
          loop: "{{ extra_folders }}"

    - name: deploy docker-compose project
      community.docker.docker_compose_v2:
        project_src: "{{ remote_project_dir }}"
        files:
          - docker-compose.yaml
        state: present
        pull: policy
        remove_orphans: true
        recreate: always
