---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://loki-prod-1.srv-prod-1.home.kinzoku.dev/loki/api/v1/push
    tls_config:
      insecure_skip_verify: true

scrape_configs:
  # local machine logs
  - job_name: local
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
  # docker logs
  - job_name: docker
    pipeline_stages:
      - docker: {}
    static_configs:
      - labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log
