---
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus-prod-1"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor-prod-1"
    scrape_interval: 5s
    static_configs:
      - targets: [cadvisor-prod-1:8080]

  - job_name: "cadvisor-prod-2"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    scrape_interval: 5s
    static_configs:
      - targets: [cadvisor-prod-2.srv-prod-2.home.kinzoku.dev:443]

  - job_name: "srv-prod-1"
    scrape_interval: 15s
    static_configs:
      - targets: [srv-prod-1.home.kinzoku.dev:9100]

  - job_name: "srv-prod-2"
    scrape_interval: 15s
    static_configs:
      - targets: [srv-prod-2.home.kinzoku.dev:9100]

  - job_name: "srv-prod-3"
    scrape_interval: 15s
    static_configs:
      - targets: [srv-prod-3.home.kinzoku.dev:9100]

  - job_name: "srv-prod-4"
    scrape_interval: 15s
    static_configs:
      - targets: [srv-prod-4.home.kinzoku.dev:9100]

  - job_name: "pve-prod-1"
    scrape_interval: 15s
    static_configs:
      - targets: ["pve-prod-1.home.kinzoku.dev:9100"]

  - job_name: "pve-prod-2"
    scrape_interval: 15s
    static_configs:
      - targets: ["pve-prod-2.home.kinzoku.dev:9100"]

  # Example job for node_exporter
  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: ['node_exporter:9100']

  # Example job for cadvisor
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
