---
networks:
  frontend:
    external: true
  backend:
    external: true
volumes:
  influxdb2-data:
services:
  influxdb:
    container_name: ixdb-prod-1
    image: influxdb:2.7.6-alpine
    ports:
      - "8086:8086"
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - /etc/influxdb2:/etc/influxdb2
      - /etc/ssl/cert.pem/:/etc/ssl/cert.pem
      - /etc/ssl/cert-key.pem/:/etc/ssl/cert-key.pem
    command: influxd --tls-cert=/etc/ssl/cert.pem --tls-key=/etc/ssl/cert-key.pem
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.services.ixdb-prod-1.loadbalancer.server.port=8086
      - traefik.http.services.ixdb-prod-1.loadbalancer.server.scheme=https
      - traefik.http.routers.ixdb-prod-1-https.entrypoints=websecure
      - traefik.http.routers.ixdb-prod-1-https.rule=Host(`ixdb-prod-1.srv-prod-2.home.kinzoku.dev`)
      - traefik.http.routers.ixdb-prod-1-https.tls=true
      - traefik.http.routers.ixdb-prod-1-https.tls.certresolver=cloudflare
    networks:
      - frontend
      - backend
    restart: unless-stopped
