---
name: Update Docker Compose File

on:
  push:
    branches:
      - main
      - test
      - dev
    paths:
      - "dns/dns-prod-1/docker-compose.yaml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload new Docker Compose File
        uses: appleboy/scp-action@master
        with:
          username: kinzoku
          host: srv-prod-3.home.kinzoku.dev
          key: ${{ secrets.SSH_KINZOKU }}
          source: "./dns/dns-prod-1/docker-compose.yaml"
          target: "/home/kinzoku/dns-prod-1/"
          strip_components: 3

      - name: Restart Docker Container
        uses: fifsky/ssh-action@master
        with:
          user: kinzoku
          host: srv-prod-3.home.kinzoku.dev
          key: ${{ secrets.SSH_KINZOKU }}
          command: |
            cd dns-prod-1
            docker compose up -d --force-recreate
